DEFAULT_BG_COLOR = "#343A40"
DEFAULT_UI_TEXT_COLOR = "#F8F9FA"
DEFAULT_BUTTON_COLOR = "#6C757D"

RADIUS = 16
BOX_SIZE = 10
DEFAULT_OUTLINE_COLOR = "#000000"
DEFAULT_TEXT_COLOR = "#000000"
DEFAULT_FILL_COLOR = "#FFFFFF"
DEFAULT_WIDTH = 2

EDGE_TAG = "edge"
VERTEX_TAG = "vertex"
EDGE_LABEL_TAG = "edge_label"