DEFAULT_BG_COLOR = "#E9E9E9"
DEFAULT_UI_TEXT_COLOR = "#141414"
DEFAULT_BUTTON_COLOR = "#C3C3C3"
DEFAULT_DROPDOWN_BUTTON_COLOR = "#EEEEEE"

RADIUS = 16
BOX_SIZE = 6
NUM_AUTOTEST_QUESTION = 5
DEFAULT_OUTLINE_COLOR = "#000000"
DEFAULT_TEXT_COLOR = "#000000"
DEFAULT_FILL_COLOR = "#FFFFFF"
DEFAULT_ALGORITHM_FILL = "#09FF00"
DEFAULT_ALGORITHM_NOT_FOCUSED = "#ECECEC"
DEFAULT_ALGORITHM_NOT_SELECTED = "#F30000"
DEFAULT_ALGORITHM_TEXT_FILL = "#FFFFFF"
DEFAULT_CORRECT_ANSWER = "#CCDECB"
DEFAULT_INCORRECT_ANSWER = "#DAC2C2"
DEFAULT_WIDTH = 2

EDGE_TAG = "edge"
VERTEX_TAG = "vertex"
EDGE_LABEL_TAG = "edge_label"