DEFAULT_BG_COLOR = "#E9E9E9"
DEFAULT_UI_TEXT_COLOR = "#141414"
DEFAULT_BUTTON_COLOR = "#C3C3C3"
DEFAULT_DROPDOWN_BUTTON_COLOR = "#EEEEEE"

RADIUS = 16
BOX_SIZE = 6
DEFAULT_OUTLINE_COLOR = "#000000"
DEFAULT_TEXT_COLOR = "#000000"
DEFAULT_FILL_COLOR = "#FFFFFF"
DEFAULT_ALGORITHM_FILL = "#00A800"
DEFAULT_WIDTH = 2

EDGE_TAG = "edge"
VERTEX_TAG = "vertex"
EDGE_LABEL_TAG = "edge_label"